# Generated by Django 5.2.4 on 2025-11-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='colorfilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
            ],
        ),
    ]
