# Generated by Django 5.2.4 on 2025-12-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_detail_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='colorfilter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.colorfilter1'),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='sizefilter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sizefilter'),
        ),
    ]
