# Generated by Django 5.2.4 on 2025-12-18 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_product_detail_colorfilter1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='sizefilter',
        ),
        migrations.CreateModel(
            name='pricefilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range', models.CharField(max_length=50)),
                ('product_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product_detail')),
            ],
        ),
    ]
